[TMP] Check cpu_ibex

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -15,75 +15,75 @@ env:
   VERILATOR_VERSION: "4.200"
 
 jobs:
-  build:
-    strategy:
-      fail-fast: false
-      matrix:
-        config:
-          - { arch: "x86_64", os: "ubuntu-latest"  }
-          - { arch: "x86_64", os: "macos-latest"   }
-          - { arch: "x86_64", os: "windows-latest" }
-    defaults:
-      run:
-        shell: bash
-    runs-on: ${{ matrix.config.os }}
-    steps:
-      - uses: actions/checkout@v3
-      - uses: actions/cache@v3
-        with:
-          path: ccache
-          key: ${{ runner.os }}-${{ matrix.config.arch }}
+  # build:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       config:
+  #         - { arch: "x86_64", os: "ubuntu-latest"  }
+  #         - { arch: "x86_64", os: "macos-latest"   }
+  #         - { arch: "x86_64", os: "windows-latest" }
+  #   defaults:
+  #     run:
+  #       shell: bash
+  #   runs-on: ${{ matrix.config.os }}
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - uses: actions/cache@v3
+  #       with:
+  #         path: ccache
+  #         key: ${{ runner.os }}-${{ matrix.config.arch }}
 
-      - name: Setup MSYS2
-        uses: msys2/setup-msys2@v2
-        if: ${{ runner.os == 'Windows' }}
-        with:
-          update: true
-          install: >-
-            git
-            mingw-w64-x86_64-cmake
-            mingw-w64-x86_64-gcc
-            mingw-w64-x86_64-make
-            patch
+  #     - name: Setup MSYS2
+  #       uses: msys2/setup-msys2@v2
+  #       if: ${{ runner.os == 'Windows' }}
+  #       with:
+  #         update: true
+  #         install: >-
+  #           git
+  #           mingw-w64-x86_64-cmake
+  #           mingw-w64-x86_64-gcc
+  #           mingw-w64-x86_64-make
+  #           patch
 
-      - name: Download and build Renode
-        run: |
-          set -ex
-          RUNNER_OS=${{ runner.os }}
-          source .github/scripts/build-renode.sh
-          mkdir -p artifacts
-          tar -czf artifacts/renode.tar.gz renode/
+  #     - name: Download and build Renode
+  #       run: |
+  #         set -ex
+  #         RUNNER_OS=${{ runner.os }}
+  #         source .github/scripts/build-renode.sh
+  #         mkdir -p artifacts
+  #         tar -czf artifacts/renode.tar.gz renode/
 
-      - name: Build peripherals for Windows
-        if: ${{ runner.os == 'Windows' }}
-        shell: msys2 {0}
-        run: |
-          set -ex
-          RUNNER_OS="Windows"
-          MAKE_BIN="mingw32-make.exe"
-          BUILD_ARCH=${{ matrix.config.arch }}
-          git submodule update --init --recursive
-          source .github/scripts/build-verilator.sh
-          source .github/scripts/build.sh
+  #     - name: Build peripherals for Windows
+  #       if: ${{ runner.os == 'Windows' }}
+  #       shell: msys2 {0}
+  #       run: |
+  #         set -ex
+  #         RUNNER_OS="Windows"
+  #         MAKE_BIN="mingw32-make.exe"
+  #         BUILD_ARCH=${{ matrix.config.arch }}
+  #         git submodule update --init --recursive
+  #         source .github/scripts/build-verilator.sh
+  #         source .github/scripts/build.sh
 
-      - name: Build peripherals for ${{ runner.os }}
-        if: ${{ runner.os != 'Windows' }}
-        run: |
-          set -ex
-          RUNNER_OS=${{ runner.os }}
-          MAKE_BIN="make"
-          BUILD_ARCH=${{ matrix.config.arch }}
-          git submodule update --init --recursive
-          source .github/scripts/build-verilator.sh
-          source .github/scripts/build.sh
+  #     - name: Build peripherals for ${{ runner.os }}
+  #       if: ${{ runner.os != 'Windows' }}
+  #       run: |
+  #         set -ex
+  #         RUNNER_OS=${{ runner.os }}
+  #         MAKE_BIN="make"
+  #         BUILD_ARCH=${{ matrix.config.arch }}
+  #         git submodule update --init --recursive
+  #         source .github/scripts/build-verilator.sh
+  #         source .github/scripts/build.sh
 
-      - uses: actions/upload-artifact@v3
-        with:
-          name: renode-verilator-integration-${{ runner.os }}-${{ matrix.config.arch }}-${{ github.run_id }}
-          path: artifacts/*
+  #     - uses: actions/upload-artifact@v3
+  #       with:
+  #         name: renode-verilator-integration-${{ runner.os }}-${{ matrix.config.arch }}-${{ github.run_id }}
+  #         path: artifacts/*
 
   test:
-    needs: build
+    # needs: build
     strategy:
       fail-fast: false
       matrix:
@@ -97,10 +97,19 @@ jobs:
     runs-on: ${{ matrix.config.os }}
     steps:
       - uses: actions/checkout@v3
-      - uses: actions/download-artifact@v3
+      - uses: dawidd6/action-download-artifact@v2
         with:
-          name: renode-verilator-integration-${{ runner.os }}-${{ matrix.config.arch }}-${{ github.run_id }}
-          path: artifacts
+          run_id: 5465819181
+
+      - name: Prepare artifacts for Linux
+        if: ${{ runner.os == 'Linux' }}
+        run: |
+          mv renode-verilator-integration-Linux-x86_64-5465819181 artifacts
+
+      - name: Prepare artifacts for Windows
+        if: ${{ runner.os == 'Windows' }}
+        run: |
+          mv renode-verilator-integration-Windows-x86_64-5465819181 artifacts
 
       - name: Test peripherals for ${{ runner.os }}
         run: |
